# Generated by Django 3.0.5 on 2020-04-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_auto_20200427_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabword',
            name='audioClip',
            field=models.FileField(blank=True, null=True, upload_to='vocab/audio/'),
        ),
    ]
