# Generated by Django 3.0.5 on 2020-04-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_lessonresource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonResource',
            new_name='Resource',
        ),
    ]
