# Generated by Django 3.0.5 on 2020-04-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_auto_20200407_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(null=True),
        ),
    ]
