# Generated by Django 3.0.5 on 2020-04-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_auto_20200407_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_logged_on',
            field=models.DateTimeField(),
        ),
    ]
