# Generated by Django 3.0.5 on 2020-04-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_auto_20200407_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
