# Generated by Django 3.0.5 on 2020-04-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_auto_20200408_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_logged_on',
        ),
    ]
