# Generated by Django 3.0.5 on 2020-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_auto_20200409_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('QZ', 'Quiz'), ('FL', 'File'), ('UR', 'URL')], default='UR', max_length=2),
        ),
    ]
