# Generated by Django 3.0.5 on 2020-04-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctAnswer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
