# Generated by Django 3.0.5 on 2020-04-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20200417_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(blank=True, choices=[('TF', 'Text Field'), ('RB', 'Radio Button')], default='TF', max_length=2),
        ),
    ]
