# Generated by Django 3.0.5 on 2020-04-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20200417_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='correctAnswer',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(choices=[('TF', 'Text Field'), ('RB', 'Radio Button')], default='TF', max_length=2),
        ),
    ]
